### ISSUE TITLE
Problems for rdc_slam catkin_make

### ISSUE THREAD

**Issue by liukeq** [sysuxyt/RDC_SLAM#2]
In rdc_slam/include/mapOptimization.h, I can't find #include #include "lego_loam/OutputMap.h", #include "lego_loam/OutputTraj.h", #include "lego_loam/OutputSepNodePcd.h" in your codes. Could you provide the codes for that?

**Comment by sysuxyt** [comment]
These are ROS services and can be generated during the compiling.

**Comment by sysuxyt** [comment]
Thanks for following this work. The code was completed nearly three years ago, and the code structure may be a little messy. I tried to refine the code last year, but busy with other things gave up halfway. I may try to renew the code recently. If any problems, contact me. And sorry for the troubles encountered when using this code.

**Comment by liukeq** [comment]
Thanks for your answers. I've solved that!
